server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:192.168.0.18}:5432/${DB_NAME:clines}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate

cors:
  allowed:
    origins: ${CORS_HOST:http://localhost:3000}
    all-methods: true
    all-headers: true
    send-credentials: true